name: Pull Request

on:
  pull_request:
    branches:
    - master

jobs:
  test:
    name: E2E
    runs-on: macOS-15-xlarge
    environment: PR
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify WWDR cert is installed
        run: |
          security find-certificate -a -c "Apple Worldwide Developer Relations Certification Authority" /Library/Keychains/System.keychain

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'

      - name: Clean Derived Data
        run: rm -rf ~/Library/Developer/Xcode/DerivedData/*

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Install Maestro
        run: |
          brew tap facebook/fb
          brew install facebook/fb/idb-companion
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - run: npx envinfo

      - name: Start dev server
        run: make start-dev-server
        env:
          BT_API_KEY_PVT: ${{ secrets.BT_API_KEY_PVT }}
      
      - name: Testing with ThreeDSTester app
        run: make integration-test
        env:
          BT_API_KEY_PUB: ${{ secrets.BT_API_KEY_PUB }}

      - name: Generate Report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: E2E Report (31, x86_64, default)
          path: |
            ${{ github.workspace }}/*.mp4
            ${{ github.workspace }}/*.mov
            ${{ github.workspace }}/*.png
            ${{ github.workspace }}/report*.xml
            ~/.maestro/tests/**/*
            /private/tmp/*.tar.gz
            ~/Library/Logs/DiagnosticReports/*
